#ifndef CONFIG_H
#define CONFIG_H

#define INIT_ACCOUNT_BALANCE 100000
#define GOODWILL_WINNING_VALUE 1000000

#define ENGINNER_EFFICIENCY 20
#define ENGINNER_SALARY 11000

#define MARKETER_EFFICIENCY 30
#define MARKETER_SALARY 8000

#define STOREMAN_EFFICIENCY 20
#define STOREMAN_SALARY 6000

#define WORKER_EFFICIENCY 20
#define WORKER_SALARY 5000

#define LOAN_LIMIT_COEFFICIENT 3

#endif // !CONFIG_H
